### ISSUE TITLE
IPython shell command failure

### ISSUE THREAD

**Issue by tbirdso** [thewtex/ngff-zarr#37]
## Overview

Attempting to run ngff-zarr from an IPython cell in Jupyter Notebook yields an error.

## Steps to Reproduce

In a Jupyter Notebook cell:
```py
!ngff-zarr -i "path/to/image.nii.gz" -o "path/to/image.zarr"
```

## Expected behavior

CLI runs and OME-Zarr image is generated successfully

## Observed behavior

```py
Traceback (most recent call last):
  File "C:\venvs\venv-itk\lib\site-packages\rich\live.py", line 122, in start
    self.refresh()
  File "C:\venvs\venv-itk\lib\site-packages\rich\live.py", line 241, in refresh
    with self.console:
  File "C:\venvs\venv-itk\lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\venvs\venv-itk\lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\venvs\venv-itk\lib\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\venvs\venv-itk\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\venvs\venv-itk\lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\venvs\venv-itk\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\tom.birdsong\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-2: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tom.birdsong\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tom.birdsong\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\venvs\venv-itk\Scripts\ngff-zarr.exe\__main__.py", line 7, in <module>
  File "C:\venvs\venv-itk\lib\site-packages\ngff_zarr\cli.py", line 192, in main
    with Live(initial, console=console) as live:
  File "C:\venvs\venv-itk\lib\site-packages\rich\live.py", line 166, in __enter__
    self.start(refresh=self._renderable is not None)
  File "C:\venvs\venv-itk\lib\site-packages\rich\live.py", line 128, in start
    self.stop()
  File "C:\venvs\venv-itk\lib\site-packages\rich\live.py", line 147, in stop
    with self.console:
  File "C:\venvs\venv-itk\lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\venvs\venv-itk\lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\venvs\venv-itk\lib\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\venvs\venv-itk\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\venvs\venv-itk\lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\venvs\venv-itk\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\tom.birdsong\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-2: character maps to <undefined>
```

**Comment by dstansby** [comment]
I'm getting the same error, but with `ngff-zarr` installed in a conda environment, and running in git-bash on Windows. Perhaps this is a Windows issue?

**Comment by thewtex** [comment]
@tbirdso @dstansby thanks for the report.

I tried to reproduce on Windows in both PowerShell and Git Bash, but I could not.

[AI says](https://www.perplexity.ai/search/how-to-address-traceback-most-oOx88yFFSQCyR098xgD3Lg) a workaround is use a modern terminal emulator, such as Windows Terminal, or set encoding to UTF-8.

A more graceful approach may be to use a different Rich Console in the environments where this occurs.
